# docker-compose.yml
version: '3.8'
services:
  web:
    build: .
    image: ghcr.io/arqpdatateam/airviz_borden:latest
    container_name: airviz_borden
    restart: always
    ports:
      - "80:8080"
    